version: '3.1'

services:

  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: app-nodejs
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/data/node_mongo/app
    ports:
      - "9091:9091"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root9118
    ports:
      - 27017:27017


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:root9118@mongo:27017/
    depends_on:
      - mongo